# Generated by Django 3.2.5 on 2024-03-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('auth', models.CharField(max_length=59)),
                ('read_by', models.CharField(max_length=59)),
            ],
        ),
    ]
